services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres 
    ports:
      - "5432:5432"
    volumes:
      - ./priv/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hello_dev
